version: '3'
services:
  spring-demo:
    image: spring-demo:1.0.0-SNAPSHOT
    build:
      context: ../spring-demo
      dockerfile: Dockerfile.x86_64
    network_mode: "host"
    ports:
      - "8081:8081"
  spring-proxy:
    image: spring-proxy:1.0.0-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8088:8088"