version: '2'

services:
  zookeeper:
    #image: 'docker.io/bitnami/zookeeper:3-debian-10'
    image: 'docker.io/bitnami/zookeeper:3.6.2'
    network_mode: "host"
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    #image: 'docker.io/bitnami/kafka:2-debian-10'
    image: 'docker.io/bitnami/kafka:2.6.0'
    network_mode: "host"
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      #- KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local