# This workflow will build a Java project with Gradle
name: Build and Test

on:
  push:
    branches: [ java-17 ]
  pull_request:
    branches: [ java-17 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: gradle -version
      - name: Run Gradle Build and tests
        run: gradle clean build test
      - name: Run and Build API first example
        run: gradle --build-file spring-api-first/build.gradle clean openApiGenerate build test
